add: api to homepage
bpaquier/sansa-project-hetic pull request #159
Opened 2022-07-11 16:00 UTC by njsen

[App] Connecting the API to the home page #121

## Fixes

Fixes #121

## Description

Ajout des données de l'api dans la homepage (nombre de douches, toilettes, etc.) + updates des design

## Démo

<img width="318" alt="Capture d’écran 2022-07-11 à 17 58 05" src="https://user-images.githubusercontent.com/71784091/178306718-3cf886ba-e0f0-4884-84f1-d7fa31816853.png">

<img width="1079" alt="Capture d’écran 2022-07-11 à 17 59 24" src="https://user-images.githubusercontent.com/71784091/178306946-c14938b7-558b-4966-984a-e2f9a4d20db7.png">

2022-07-11 18:42 UTC, Klochette approved these changes
looks good to me :)

2022-07-12 07:38 UTC, bpaquier requested changes

2022-07-12 07:38 UTC, bpaquier commented on src/Views/Account/Home/index.tsx
> +
Hello Nico, 
Hugo a fait une route api pour avoir tous les services et leur nombre: 
https://sansah.vhswebs.com/api/getservice/count
Doc de l'api => https://sansah.vhswebs.com/api/qZ2jFqj=/doc.

Du coup il faudrait ajouter une nouvelle méthode dans useApi et l'utiliser ici:)

2022-07-12 10:23 UTC, bpaquier approved these changes

2022-07-12 11:50 UTC, ConstancePetillot commented
@njsen 
Première partie ok sur le display des bonnes infos sur la home.

Reste à connecter les bouton pour qu'au press sur une card, on affiche la map avec les bon points d'intêret.
Exemple : Si je clique sur le 25 douches publiques, j'arrive sur la carte et les lieux des 25 douches sont affichés.

2022-07-13 11:28 UTC, Klochette submitted a review, later dismissed

2022-07-13 11:28 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +                onPress={() => navigate("/")}
Faut que tu linkes !

2022-07-13 11:28 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            onPress={() => navigate("/")}
Faut que tu linkes !

2022-07-13 12:26 UTC, merged