fix: borne nav bar
bpaquier/sansa-project-hetic pull request #72
Opened 2022-06-27 08:09 UTC by njsen

71/NavigationBorne - Bug d'affichage

## Fixes

Résolution du bug d'affichage de la barre de navigation borne

Fixes #71 

## Démo

Avant :
<img width="1440" alt="Capture d’écran 2022-06-27 à 09 58 20" src="https://user-images.githubusercontent.com/71784091/175893763-cbce7d17-8ea0-49c9-90c4-cae094b5d0c4.png">

Après :
<img width="1440" alt="Capture d’écran 2022-06-27 à 09 56 32" src="https://user-images.githubusercontent.com/71784091/175891272-cc9f17e2-1e3c-4121-8a3f-df5261732684.png">

2022-06-27 08:11 UTC, njsen commented on babel.config.js
> -  api?.cache(true);
```
The project's Babel config is invalid: /Users/njesen/Desktop/sansa-project-hetic/babel.config.js: Error while loading config - Unexpected token '.'
/Users/njesen/Desktop/sansa-project-hetic/babel.config.js: Error while loading config - Unexpected token '.'
/Users/njesen/Desktop/sansa-project-hetic/babel.config.js:5
  api?.cache(true);
```

2022-06-28 08:31 UTC, Klochette requested changes

2022-06-28 08:31 UTC, Klochette commented on src/Components/Navigation/NavigationBorne/index.tsx
>        <View>
Je t'ai envoyé la modification par discord ! 
Aussi, tu as du style dans le html (ligne 20, 32, 44, et ailleurs peut être ?) est ce que tu peux les ajouter dans ton fichier de style s'il te plait ?
Je sais que c'est pas toi mais pour que ce soit plus clean en général, vaut mieux les mettre dans le style.ts et ne pas utiliser de style dans le html :)

2022-06-28 08:32 UTC, Klochette requested changes

2022-06-28 08:32 UTC, Klochette commented on src/Components/Navigation/NavigationBorne/index.tsx
>        </View>
Je t'ai envoyé la modification par discord ! 
Aussi, tu as du style dans le html (ligne 20, 32, 44, et ailleurs peut être ?) est ce que tu peux les ajouter dans ton fichier de style s'il te plait ?
Je sais que c'est pas toi mais pour que ce soit plus clean en général, vaut mieux les mettre dans le style.ts et ne pas utiliser de style dans le html :)

2022-06-28 11:39 UTC, Klochette requested changes

2022-06-28 11:39 UTC, Klochette commented on src/Components/Navigation/NavigationBorne/styles.ts
>      `
```suggestion
  ${({ active }) =>
      active && `border-color: ${Theme.color.primary.blueExtraDark};`};
  
  ${({ spaceTop }) => spaceTop && `margin-top: 28px;`};
```

2022-06-28 11:39 UTC, Klochette commented on src/Components/Navigation/NavigationBorne/styles.ts
> +  `};
```suggestion
  ${({ active }) =>
    active && `background-color: ${Theme.color.primary.blueExtraDark};`};
```

2022-06-28 11:39 UTC, Klochette commented on src/Components/Navigation/NavigationBorne/styles.ts
> +  align-items: center;
❤️

2022-06-28 12:19 UTC, merged