78/feat-homepage
bpaquier/sansa-project-hetic pull request #85
Opened 2022-06-30 13:29 UTC by njsen

## Feat

Ajout de la homepage borne et mobile

#78 

## Description

Ajout de la homepage borne et mobile

## Démo
<img width="1076" alt="Capture d’écran 2022-06-30 à 15 25 01" src="https://user-images.githubusercontent.com/71784091/176689312-38a69541-d9c7-4855-aba7-5806c08b9f06.png">
<img width="318" alt="Capture d’écran 2022-06-30 à 15 25 46" src="https://user-images.githubusercontent.com/71784091/176689326-853926a0-1f11-4205-b5b7-4aed4f6f70d6.png">
<img width="321" alt="Capture d’écran 2022-06-30 à 15 25 57" src="https://user-images.githubusercontent.com/71784091/176689345-a567ec8e-78ea-4c2e-9edf-4ee71336766b.png">

2022-07-01 08:53 UTC, Klochette approved these changes
C'est nickel sinon !
Par contre, si motiv tu as, rebase sur ma branche `feat/languages` et ajoute tes traductions :D bien joué pour les rows, faut que je retouche pour faire la même

2022-07-01 08:53 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +                  style={{ width: "100%", height: "100%" }}
t'es obligé de laisser le style en inline comme ça ou pas ? Sinon vaut mieux le mettre dans ton `./styles.ts`

2022-07-01 08:53 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +  EventCardTitleWrapper,
en vrai si t'es chaud, rebase sur ma branche et prend mon component `<TextWrapper />` ? Comme ça c'est un minimum refacto 🙄 si t'as le temps et l'envie of course

2022-07-01 08:53 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +              <TouchableOpacity onPress={() => navigate("/")}>
J'avais pas vuuuuu ce component... Je vais faire pareil pour la Plus page, je le met en todo... GG !

2022-07-01 08:53 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +        <SecondRow>
SOOOOOO SMART

2022-07-01 08:54 UTC, Klochette requested changes
Pardon j'ai mis oui, mais faut que tu mettes tes box shadows en fait

2022-07-01 10:59 UTC, ConstancePetillot commented
@njsen 
L'icône me semble plus grosse que sur la maquette, tu as moyen e la réduire un peu (sur borne, pas encore regardé su rmobile)
![image](https://user-images.githubusercontent.com/56641493/176881874-3cec9228-4f1b-4f9c-a261-86a0aebf9d47.png)

Sinon c'est super propre !

2022-07-04 23:36 UTC, njsen commented
J'ai fix la carte santé et rajouté les shadows, je rajouterai la traduction dans une nouvelle PR

2022-07-05 08:24 UTC, Klochette approved these changes
💯

2022-07-05 09:22 UTC, Klochette requested changes
Et tu as oublié les boxShadows sur mobile aussi D: Désolée pour le changement d'avis

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <MapCard>
```suggestion
            <MapCard style={boxShadow.panelAndroid}>
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +const { color } = Theme;
```suggestion
const { color, boxShadow } = Theme;
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <EventCard>
```suggestion
            <EventCard style={boxShadow.panelAndroid}>
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <SanitaryCard>
```suggestion
            <SanitaryCard style={boxShadow.panelAndroid}>
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <AssociationsCard>
```suggestion
            <AssociationsCard style={boxShadow.panelAndroid}>
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <SportCard backgroundColor="blue">
```suggestion
            <SportCard style={boxShadow.panelAndroid} backgroundColor="blue">
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +            <HealthCard>
```suggestion
            <HealthCard style={boxShadow.panelAndroid}>
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/index.tsx
> +                Où puis-je me rendre ?{" "}
```suggestion
                Où puis-je me rendre ?
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/styles.ts
> +  ...boxShadow.panelAndroid
```suggestion
```

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/styles.ts
> +  ...boxShadow.panelAndroid
Tu peux supprimer cette ligne

2022-07-05 09:22 UTC, Klochette commented on src/Components/Home/HomeBorne/styles.ts
> +const { color, boxShadow } = Theme;
```suggestion
const { color } = Theme;
```

2022-07-05 09:26 UTC, Klochette requested changes

2022-07-05 09:26 UTC, Klochette commented on src/Components/Home/HomeMobile/index.tsx
> +          <HealthCard>
```suggestion
          <HealthCard style={boxShadow.panelAndroid}>
```

2022-07-05 10:45 UTC, Klochette approved these changes

2022-07-05 14:51 UTC, merged